### ISSUE TITLE
Time zone offset plus-minus

### ISSUE THREAD

**Issue by gjhyt** [skaringa/tzdataservice#1]
@skaringa 
Hi and thanks for the code!

I wanted to ask though.

You have:
` return (int) Math.floor((lon - 7.500000001) / 15) + 1;`

In case (lon-7.5) is >0 we are ok, floor will work as supposed.
But, in case (lon-7.5) <0 , we must use ceil in order to go down.

Also, in ` tzname = String.format("Etc/GMT%+d", -tzOffset);` 
Why do you use minus?  `-tzOffset` ?

If, for example we use longitude = -125, then tzOffset will be < 0, and you use ` -tzOffset` in the format, so `GMT is GMT + `.
But, at this longitude (west), the GMT is minus (GMT-8 for example).

Am I missing something?

Thanks!

**Comment by skaringa** [comment]
For Etc timezones, positive numbers count hours west of GMT. See https://en.wikipedia.org/wiki/Tz_database#Area for an explanation or http://twiki.org/cgi-bin/xtra/tzdate?tz=Etc/GMT+1 for an example.
The code is working perfect for positive and negative longitudes. It is ensured by the JUnit test [TzDataEtcTest.java
](https://github.com/skaringa/tzdataservice/blob/master/test/de/kompf/tzdata/TzDataEtcTest.java) 
If you would read and understand the whole code then you would get tzOffset -8 for your example longitude -125 (or Etc/GMT+8) which is absolutely correct.
